FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Fix permissions explicitly (WSL-safe)
RUN chmod +x node_modules/.bin/react-scripts

CMD ["npm", "start"]